version: '3'
services:
        backend:
                build:  ./src/backend
                ports:
                        - "8000:8000"
                volumes: 
                        - ./src/backend:/usr/src/app
                tty: true